name: Android Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4724:4723
        options: >-
          --name appium
          --shm-size 2g

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: '30.0.3'
        target: default

    - name: Create and start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Pixel_5
        avd-name: test
        emulator-options: '-no-window -no-snapshot'
        cores: 2
        force-avd-creation: true
        emulator-boot-timeout: 600
        disable-animations: true
        disable-spellchecker: false
        disable-linux-hw-accel: true
        enable-hw-keyboard: false
        channel: stable
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.23-9/x64

    - name: Wait for Emulator to be ready
      run: |
        echo "Waiting for emulator to be ready..."
        timeout 300s adb wait-for-device
        adb shell getprop sys.boot_completed
      continue-on-error: true

    - name: Run Appium server
      run: |
        docker run -d -p 4724:4723 appium/appium
        sleep 15

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium CLI
      run: npm install -g appium

    - name: Install Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'maven'

    - name: Install Maven dependencies
      run: mvn install

    - name: Run tests
      run: mvn test
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        AVD_NAME: test
        DEVICE: emulator-5554

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/



